### ISSUE TITLE
Linux: failures in "configure" subcommand

### ISSUE THREAD

**Issue by derrickstolee** [microsoft/Git-Credential-Manager-Core#161]
I was testing GCM Core on my Linux machine, when I ran into a couple errors:

```sh
stolee@stolee-linux-metal:/_git/office/src$ GCM_TRACE=1 git-credential-manager-core configure
13:04:35.696346 ...er/Application.cs:69 trace: [RunInternalAsync] Git Credential Manager version 2.0.214-beta+2e9919d0b8 (Linux, .NET Core 3.1.7) 'configure'
13:04:35.719149 ...rationService.cs:124 trace: [RunAsync] Configuring component 'Git Credential Manager'...
Configuring component 'Git Credential Manager'...
fatal: Index was outside the bounds of the array.

stolee@stolee-linux-metal:/_git/office/src$ git config --unset credential.helper

stolee@stolee-linux-metal:/_git/office/src$ GCM_TRACE=1 git-credential-manager-core configure
13:04:57.168842 ...er/Application.cs:69 trace: [RunInternalAsync] Git Credential Manager version 2.0.214-beta+2e9919d0b8 (Linux, .NET Core 3.1.7) 'configure'
13:04:57.192033 ...rationService.cs:124 trace: [RunAsync] Configuring component 'Git Credential Manager'...
Configuring component 'Git Credential Manager'...
fatal: Failed to get Git configuration multi-valued entry 'credential.helper' with value regex '.*'. Exit code '1' (level=All)
```

**Comment by derrickstolee** [comment]
For the index out-of-bounds, I found this stack trace:

```
Index was outside the bounds of the array.
   at Microsoft.Git.CredentialManager.GitProcessConfiguration.GetRegex(String nameRegex, String valueRegex)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Git.CredentialManager.Application.Microsoft.Git.CredentialManager.IConfigurableComponent.ConfigureAsync(IEnvironment environment, EnvironmentVariableTarget environmentTarget, IGit git, GitConfigurationLevel configurationLevel) in /_scratch/gcm-core/src/shared/Microsoft.Git.CredentialManager/Application.cs:line 179
   at Microsoft.Git.CredentialManager.ConfigurationService.RunAsync(ConfigurationTarget target, Boolean configure) in /_scratch/gcm-core/src/shared/Microsoft.Git.CredentialManager/ConfigurationService.cs:line 127
```
