### ISSUE TITLE
frequent System.Threading.Tasks crashes w/ macOS Big Sur

### ISSUE THREAD

**Issue by jaz2038** [microsoft/Git-Credential-Manager-Core#250]
**Which version of GCM Core are you using?**
Git Credential Manager version 2.0.289-beta+22bd06dc57 (macOS, .NET Core 3.1.10)

From a terminal, run `git-credential-manager-core version` and paste the output.

**Which Git host provider are you trying to connect to?**

* [x] Azure DevOps
* [ ] Azure DevOps Server (TFS/on-prem)
* [ ] GitHub
* [ ] GitHub Enterprise
* [ ] Bitbucket
* [ ] Other - please describe

**Can you access the remote repository directly in the browser using the remote URL?**

From a terminal, run `git remote -v` to see your remote URL.

* [x] Yes
* [ ] No, I get a permission error
* [ ] No, for a different reason - please describe

---

**_[Azure DevOps only]_ What format is your remote URL?**

* [ ] Not applicable
* [ ] https://dev.azure.com/`{org}`/...
* [x] https://`{org}`@dev.azure.com/`{org}`/...
* [ ] https://`{org}`.visualstudio.com/...

**_[Azure DevOps only]_ If the account picker shows more than one identity as you authenticate, check that you selected the same one that has access on the web.**

* [x] Not applicable
* [ ] I only see one identity
* [ ] I checked each identity and none worked

---

**Expected behavior**

I am authenticated and my Git operation completes successfully.

**Actual behavior**

About 1/5 times after I do a git pull or git push, I get this crash - I didn't see this until I updated to macOS Big Sur (originally seen this with macOS 11.0.1, still seeing it with macOS 11.1).  After the crash I have to reauthenticate

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (0x8007001F)
File name: 'System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Diagnostics.ProcessWaitState.WaitForExit(Int32 millisecondsTimeout)
   at System.Diagnostics.Process.WaitForExitCore(Int32 milliseconds)
   at System.Diagnostics.Process.WaitForExit()
   at Microsoft.Git.CredentialManager.GitProcessConfiguration.TryGet(String name, String& value)
   at Microsoft.Git.CredentialManager.Settings.GetSettingValues(String envarName, String section, String property)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.Git.CredentialManager.Settings.TryGetSetting(String envarName, String section, String property, String& value)
   at Microsoft.Git.CredentialManager.Settings.get_CredentialNamespace()
   at Microsoft.Git.CredentialManager.CommandContext..ctor()
   at Microsoft.Git.CredentialManager.Program.Main(String[] args)
error: /usr/local/share/gcm-core/git-credential-manager-core get died of signal 6
Password for xxx: 
fatal: Authentication failed for xxx
```

(where xxx is my repo name)

**Logs**

Set the environment variables `GCM_TRACE=1` and `GIT_TRACE=1` and re-run your Git command. Review and redact any private information and attach the log.

```
06:28:57.811123 git.c:440               trace: built-in: git pull
06:28:57.824999 run-command.c:663       trace: run_command: git fetch --update-head-ok --recurse-submodules=on
06:28:57.831071 git.c:440               trace: built-in: git fetch --update-head-ok --recurse-submodules=on
06:28:57.847951 run-command.c:663       trace: run_command: GIT_DIR=.git git-remote-https origin XXX_GITREPO
06:28:58.198763 run-command.c:663       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager-core get'
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (0x8007001F)
File name: 'System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Diagnostics.ProcessWaitState.WaitForExit(Int32 millisecondsTimeout)
   at System.Diagnostics.Process.WaitForExitCore(Int32 milliseconds)
   at System.Diagnostics.Process.WaitForExit()
   at Microsoft.Git.CredentialManager.GitProcessConfiguration.TryGet(String name, String& value)
   at Microsoft.Git.CredentialManager.Settings.GetSettingValues(String envarName, String section, String property)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.Git.CredentialManager.Settings.TryGetSetting(String envarName, String section, String property, String& value)
   at Microsoft.Git.CredentialManager.Settings.get_CredentialNamespace()
   at Microsoft.Git.CredentialManager.CommandContext..ctor()
   at Microsoft.Git.CredentialManager.Program.Main(String[] args)


error: /usr/local/share/gcm-core/git-credential-manager-core get died of signal 6
Password for XXX_GITREPO:
06:29:10.839226 run-command.c:663       trace: run_command: '/usr/local/share/gcm-core/git-credential-manager-core erase'
06:29:13.375876 ...er/Application.cs:69 trace: [RunInternalAsync] Git Credential Manager version 2.0.289-beta+22bd06dc57 (macOS, .NET Core 3.1.10) 'erase'
06:29:13.392271 ...mmands/Command.cs:63 trace: [ExecuteAsync] Start 'erase' command...
06:29:13.413929 ...mmands/Command.cs:74 trace: [ExecuteAsync] Detecting host provider for input:
06:29:13.415383 ...mmands/Command.cs:75 trace: [ExecuteAsync] 	protocol=https
06:29:13.415571 ...mmands/Command.cs:75 trace: [ExecuteAsync] 	host=dev.azure.com
06:29:13.415590 ...mmands/Command.cs:75 trace: [ExecuteAsync] 	path=XXX_GITREPO
06:29:13.415597 ...mmands/Command.cs:75 trace: [ExecuteAsync] 	username=XXX_USERNAME
06:29:13.415606 ...mmands/Command.cs:75 trace: [ExecuteAsync] 	password=XXX_PWD
06:29:13.452930 ...viderRegistry.cs:129 trace: [GetProvider] Performing auto-detection of host provider.
06:29:13.454881 ...mmands/Command.cs:77 trace: [ExecuteAsync] Host provider 'Azure Repos' was selected.
06:29:13.455872 ...sHostProvider.cs:108 trace: [EraseCredentialAsync] Erasing stored credential in store with service=XXX_GITREPO account=...
06:29:13.530190 ...sHostProvider.cs:111 trace: [EraseCredentialAsync] Credential was successfully erased.
06:29:13.530255 ...mmands/Command.cs:81 trace: [ExecuteAsync] End 'erase' command...
fatal: Authentication failed for XXX_GITREPO
```

**Comment by mjcheetham** [comment]
Hello @jaz2038, thanks for reporting this!

Since you say you've "upgraded to" Big Sur, can I assume this is an Intel-based Mac, and not one of the new Apple Silicon M1 Macs?

Assuming this is an Intel Mac, can you please check if the following file exists:

```
/usr/local/share/gcm-core/System.Threading.Tasks.dll
```

Assume it does exist, are you running any anti-virus software, or running in a VM (or is there something "interesting" with your setup)?

**Comment by jaz2038** [comment]
yes correct, intel based Macbook Pro (15" 2019).  
yes that file does exist. 
yes - running an antivirus but didn't see this issue running same antivirus w/ previous macOS - I can experiment with it off to validate though.  not running anything else that's really special with my setup, no VM, etc...

**Comment by jaz2038** [comment]
@mjcheetham I see same errors w/ and w/o antivirus running.

**Comment by mjcheetham** [comment]
Hi @jaz2038, from the limited searching I've done it seems the specific error message coming from the .NET Runtime "A device attached to the system is not functioning" is due to an unknown I/O failure at the runtime-OS layer (`ERROR_GEN_FAILURE` is the runtime error value).

I'm not entirely sure how to go about debugging this issue further. Can you try any/all of the following:

1. Uninstall GCM Core and then reinstall
   - If installed via Homebrew:
     `brew --cask reinstall git-credential-manager-core`
   - Otherwise:
     `sudo /usr/local/share/gcm-core/uninstall.sh` and then download and install the [latest GCM Core release](https://aka.ms/gcmcore-latest)

2. Download the .NET SDK and see if the same error occurs on a "Hello, World!" executable?

3. ☢️ The Nuclear Option ☢️:
    Try installing macOS Big Sur fresh on another APFS volume (apparently APFS's volume handling makes this easy?) OR at least in a VM or another Mac running Big Sur.

I hate suggesting the latter option. Might also be interesting to reach out on the [dotnet/runtime](https://github.com/dotnet/runtime) repository about help with this?

**Comment by jaz2038** [comment]
@mjcheetham thx for looking deeper here - #1/reinstalling didn't help.  As for #2, I'm actually building several .net apps that aren't hitting this.  Yeah I'm hesitant to try out #3/nuclear option but I can reach out to dotnet/runtime to see if there is any possible help there.  If you have any other builds you'd like to try, I'm game for beta testing/getting more debug information for you as well.

**Comment by johnterickson** [comment]
@mjcheetham I have a 100% repro on this.  Every `git push` from my Big Sur repros this on the *first* attempt, but then works fine the second attempt.  I know this sounds crazy.  I am running Microsoft corporate Intune which does run Defender.

```
johnerickson@Filatovm18 lutcomp % git push
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (0x8007001F)
File name: 'System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Diagnostics.ProcessWaitState.WaitForExit(Int32 millisecondsTimeout)
   at System.Diagnostics.Process.WaitForExitCore(Int32 milliseconds)
   at System.Diagnostics.Process.WaitForExit()
   at Microsoft.Git.CredentialManager.GitProcessConfiguration.TryGet(String name, String& value)
   at Microsoft.Git.CredentialManager.Settings.GetSettingValues(String envarName, String section, String property)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.Git.CredentialManager.Settings.TryGetSetting(String envarName, String section, String property, String& value)
   at Microsoft.Git.CredentialManager.Settings.get_CredentialNamespace()
   at Microsoft.Git.CredentialManager.CommandContext..ctor()
   at Microsoft.Git.CredentialManager.Program.Main(String[] args)


error: /usr/local/share/gcm-core/git-credential-manager-core get died of signal 6
Username for 'https://@github.com': [[A
johnerickson@Filatovm18 lutcomp % git push
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 483 bytes | 483.00 KiB/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/johnterickson/lutcomp.git
   83ab641..7f21647  master -> master
```

**Comment by derrickstolee** [comment]
> @mjcheetham I have a 100% repro on this. Every `git push` from my Big Sur repros this on the _first_ attempt, but then works fine the second attempt.

@johnterickson: a clarification, please: do you mean first attempt per shell session? Does it repro with a new Terminal tab, or restarting Terminal app? Or do you need to restart the computer?

**Comment by johnterickson** [comment]
Great question @derrickstolee.  Of course, by saying the above I was able to jinx it and it won't happen.  I think it has something to do with time and/or sleep.  I will try to repro.  What logs info should I be capturing?  Also, if I can get a repro, I will try excluding the GCM Core folder from Mac Defender and see if that is the key.

**Comment by johnterickson** [comment]
@derrickstolee Ok the 100% (3/3) repro is to reboot and immediately try to `git push`.  

**By adding `git-credential-manager-core` to the Defender exclusion list, I no longer get the error.**

**Comment by haydenlewis** [comment]
I am experiencing a similar issue, albeit when pushing to GitHub for a project unrelated to .NET Core development.

```bash
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (0x8007001F)
File name: 'System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Diagnostics.ProcessWaitState.WaitForExit(Int32 millisecondsTimeout)
   at System.Diagnostics.Process.WaitForExitCore(Int32 milliseconds)
   at System.Diagnostics.Process.WaitForExit()
   at Microsoft.Git.CredentialManager.Interop.Posix.PosixEnvironment.TryLocateExecutable(String program, String& path)
   at Microsoft.Git.CredentialManager.EnvironmentExtensions.LocateExecutable(IEnvironment environment, String program)
   at Microsoft.Git.CredentialManager.CommandContext..ctor()
   at Microsoft.Git.CredentialManager.Program.Main(String[] args)


error: /usr/local/share/gcm-core/git-credential-manager-core get died of signal 6
```


Any suggestions to help resolve this issue would be much appreciated.

**Comment by fabiansalamo** [comment]
> git-credential-manager-core

This did it for me, as I was running defender as well.

**Comment by givinalis** [comment]
The solution by @johnterickson worked perfectly for me:
- Open Microsoft Defender (if this is running on your mac)
- Click on _Actions_ on the top bar and select _Exclusions_
- From the pop up displayed select Add new > Process then enter `git-credential-manager-core`

You should be good to go.

**Comment by haydenlewis** [comment]
I am not running Microsoft Defender, so I remain uncertain how to debug this issue.

**Comment by aaroncrespo** [comment]
I have added the exception, and still see the issue in about 3:4 git interactions.

**Comment by jmezach** [comment]
I'm suffering from the same issue. My organization isn't using Microsoft Defender but Sophos but the issues are very similar. Running git-credential-manager-core a couple of times results in different errors until at some point it just works. Then after a while the issue comes back and I need to run it again a couple of times before it magically fixes itself.

**Comment by jaz2038** [comment]
@mjcheetham  Problem is definitely related to use of antivirus (ESET in my case) - by temporarily disabling realtime protection everything works fine.   Latest errors look slightly different w/ the latest version of git-credential-manager-core that moved to .net 5 (2.0.374-beta+161775c536):

`Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Net.Sockets.SocketAsyncEngine' threw an exception.
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Concurrent, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. A device attached to the system is not functioning.
 (0x8007001F)
File name: 'System.Collections.Concurrent, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Net.Sockets.SocketAsyncEngine..ctor()
   at System.Net.Sockets.SocketAsyncEngine.CreateEngines()
   at System.Net.Sockets.SocketAsyncEngine..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Sockets.SafeSocketHandle..ctor(IntPtr preexistingHandle, Boolean ownsHandle)
   at System.Diagnostics.Process.OpenStream(Int32 fd, FileAccess access)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Git.CredentialManager.GitProcessConfiguration.TryGet(String name, String& value)
   at Microsoft.Git.CredentialManager.Settings.GetSettingValues(String envarName, String section, String property)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.Git.CredentialManager.Settings.TryGetSetting(String envarName, String section, String property, String& value)
   at Microsoft.Git.CredentialManager.Settings.get_CredentialNamespace()
   at Microsoft.Git.CredentialManager.CommandContext..ctor()
   at Microsoft.Git.CredentialManager.Program.Main(String[] args)
`

**Comment by aaroncrespo** [comment]
There are known issues with `EndpointSecurity.framework` + `git` + `open()` and SIG handling. You can try the latest Big Sur Beta to check if that's the issue, I know it helped me.

**Comment by CoooWeee** [comment]
same issue on Big Sur 11.2.3

**Comment by aaroncrespo** [comment]
I should have been more clear but check 11.3.3

**Comment by jaz2038** [comment]
@aaroncrespo thx a ton - upgrading to Big Sur 11.3 Beta 3 fixes the issue for me.

**Comment by sashaweiss** [comment]
@johnterickson great tip - that seems to be helping with me so far. (Big Sur 11.2.3, Intel Mac with Microsoft Defender running.)
